# Generated by Django 3.0.3 on 2020-02-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
                ('author', models.CharField(max_length=128, verbose_name='author')),
                ('review', models.CharField(max_length=255, verbose_name='review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.Article', verbose_name='article')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='blog.Review', verbose_name='author')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
