# Generated by Django 3.0.3 on 2020-02-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='readed',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='blog.Review', verbose_name='reply'),
        ),
    ]
