# Generated by Django 3.0.3 on 2020-02-25 13:16

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200225_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '750x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
